name: currency_conventer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  # http:
  shared_preferences: ^0.5.3+4
  provider: ^3.1.0
  chopper: ^3.0.6
  built_value: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  chopper_generator: ^3.0.6
  build_runner: ^1.11.1
  built_value_generator: ^7.1.0

dependency_overrides:
  analyzer: '0.40.4'

flutter:
  uses-material-design: true